-- 创建表
CREATE TABLE ODP_BODY_FIELDS (
    FIELD_NUMBER   NUMBER(3),
    FIELD_NAME     CHAR(80 CHAR),
    DATA_TYPE      CHAR(20 CHAR),
    DESCRIPTION    CHAR(1000 CHAR)
);

-- 创建序列（如果使用自增ID）
CREATE SEQUENCE ODP_BODY_FIELDS_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 添加注释
COMMENT ON TABLE ODP_BODY_FIELDS IS 'PDF表格数据存储表';
COMMENT ON COLUMN ODP_BODY_FIELDS.FIELD_NUMBER IS '字段编号';
COMMENT ON COLUMN ODP_BODY_FIELDS.FIELD_NAME IS '字段名称';
COMMENT ON COLUMN ODP_BODY_FIELDS.DATA_TYPE IS '数据类型';
COMMENT ON COLUMN ODP_BODY_FIELDS.DESCRIPTION IS '描述';